### ISSUE TITLE
subProceso genera "Unhandled promise rejection" cando o proceso ejecutado falla

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#12]
Exemplo para reproducir o erro:

Dentro dun proceso X chamamos a un subproceso Y sin pasar os parámetros necesarios

```js
__r(){
  return ['a']
}

a(){
  return this.subProceso('Job.job_get', {})
}
```

Resultados: 
(O subproceso se executa correctamente pero non se da manejado a devolución)
 ```
1504618618224 INFO t@0 INICIO_SUB_PROCESO  {}
EN SUBPROCESO EJECUTAR Tarea {
  id: 't@0',
  args: { proceso: 'Job.job_get' },
  sys: { __subproceso__: true, __depurar__: undefined },
  resultados: {} }
1504618618227 DEBUG t@0 RUN_PASO Job.job_get -> __validacionParametrosNecesarios {}
FALTA_PARAMETRO: id
1504618618228 ERROR t@0 ERROR Job.job_get -> __validacionParametrosNecesarios "FALTA_PARAMETRO: id"
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'get' of undefined
```

**Comment by frmadem** [comment]
Problema fixed en v2.3.2

**Comment by alambike** [comment]
Sigue fallando si el pete del subproceso es en el bloque ejecutar:

```
TypeError: Cannot read property 'getJob' of undefined
    at module.exports.__recogerInfoJob (/home/app/lib/procesos/api/job/job_get.js:24:45)
    at Promise (/home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor_paso.js:15:35)
    at Promise (<anonymous>)
    at module.exports.ejecutar (/home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor_paso.js:11:16)
    at module.exports.__r (/home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor.js:141:34)
    at /home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor.js:77:32
    at <anonymous>
1504632788964 ERROR t@0 ERROR Job.job_get -> __recogerInfoJob {}
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'get' of undefined
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by frmadem** [comment]
Era otro error, no se estaba recogiendo el estado del subproceso de forma adecuada. 

Arreglado en [v2.3.3](https://github.com/prefapp/catro_eixos_js/commit/6f6f444bc0bf020f6fda281d1f6148e34dba5b12)
