### ISSUE TITLE
Error tratando de enganchar varias promesas en un mismo paso

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#8]
```js
  __generarCompuestosMultimedia(){
    
    this._formats.forEach( (format) => {
      
      this._format = format;

      this.getPlaylistsGenerar()
        .then(() => {this.generarCompuesto()})
        .then((compuesto_generado) => this.registrarCompuestos(compuesto_generado))
     }

```

```
Unhandled rejection TypeError: Cannot read property '__depurar__' of undefined
    at module.exports (/home/app/node_modules/catro-eixos-js/lib/nucleo/ejecutor_subproceso.js:18:49)
    at module.exports.subProceso (/home/app/node_modules/catro-eixos-js/lib/nucleo/proceso.js:283:16)
    at module.exports.generarCompuesto (/home/app/lib/procesos/api/productions/production_add_media.js:144:17)
    at getPlaylistsGenerar.then (/home/app/lib/procesos/api/productions/production_add_media.js:102:27)
    at tryCatcher (/home/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by frmadem** [comment]
@alambike ¿podrías aportar más datos del código que revienta please?

**Comment by alambike** [comment]
Non volvin a ver o erro asique pecho
